### ISSUE TITLE
Requests 2024.01.26

### ISSUE THREAD

**Issue by jtuhtan** [mcrooks83/rapid_sensor_app#1]
v2 files not loading.

"Sensor version: v2 2000 Hz" instead of current "Sensor version: v2 100 Hz"

Acceleration data not showing when loading v2 files.

Legends should be "Pressure (mbar)" and "Acceleration Magnitude (g)".

The "Pressure" and "Acceleration" check boxes in top left plot menu should be default in the selected status.

**Comment by mcrooks83** [comment]
All of the above are in the lastest fix.  I am working on the HIG addition.

**Comment by mcrooks83** [comment]
See email re HIG :)
